#include<stdio.h>
#include<stdlib.h>
#include<math.h>

#include "GalCos_variables.h"

int Npart_Total,MINIMUM_MEMBERS,NGB_MAX,FOF_PROCEDURE;
int FLAG_SUBFIND,FLAG_WRITE_INDIVIDUAL_CLUSTERS;
int MINIMUM_NSUBSTRUCT,NCLUSTERS; 

float BoxSize,REDSHIFT,OMEGA_MATTER,OMEGALAMBDA,HUBBLEPARAM,OMEGABARYON;
float Llenght,COSMIC_TIME,b_Link;
float GRAV_SOFT,PARTMASS;
float *maxdist,*maxdist_tmp;

double G_INTERNAL_UNITS,LENGHT_INTERNAL_UNITS;
double VELOCITY_INTERNAL_UNITS,MASS_INTERNAL_UNITS,TIME_INTERNAL_UNITS;
double ENERGY_INTERNAL_UNITS,DENSITY_INTERNAL_UNITS,HUBBLE_INTERNAL_UNITS;


struct part *Particle=NULL;
struct halo *Halos=NULL;
struct COLA temp_cola;
struct COLA_float NGB_DISTcand;
struct COLA NGB_cand;
